---
title: "Causation_LRM_new"
author: "andrea"
date: "2020/7/27"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(readr)
library(stringr)
library(tidyverse)
library(Rling); library(rms); library(visreg); library(car)
```

```{r message=FALSE, warning=FALSE}
causation <- read_csv('causation_all.csv')

table(causation$ResuPred, causation$Varieties)

causation$ResuPred <- factor(causation$ResuPred)
causation$Property <- factor(causation$Property)
causation$Transitivity <- factor(causation$Transitivity)
causation$Varieties <- factor(causation$Varieties)

# logistic regression model
m.lrm <- lrm(ResuPred ~ Property + Transitivity + Varieties, data = causation)
m.lrm
```

```{r}
rms::vif(m.lrm)
```

```{r}
causindex <- which(causation$Transitivity == 'TR')
deleteindex <- sample(causindex, length(causindex) - 3)
causation[-deleteindex, ]
```

```{r}
m.lrm1 <- lrm(ResuPred ~ Property + Transitivity + Varieties, data = causation, 
              x = T, y = T)

validate(m.lrm1, B = 200)
```

```{r}
s <- sample(455, 100)
d.small <- causation[s, ]
m.lrm1.small <- lrm(ResuPred ~ Property + Transitivity + Varieties, data = d.small, 
                    x = T, y = T)
validate(m.lrm1.small, B = 200)
```
